### ISSUE TITLE
Bedrock skin does not show up on Java

### ISSUE THREAD

**Issue by 7man7LMYT** [GeyserMC/Floodgate#182]
Whenever I join a Floodgate enabled server with my bedrock account, I join fine.
However, my bedrock skin refuses to show up to anybody who is not a fellow Geyser player despite my skin having gone through the queue. I have checked myself and it appears to return my actual skin on Bedrock. Oddly enough, my own server does show my skin for other Java players, but it doesn't show up on any other server. (Some small SMP servers, Minehut, Local Test Servers, A building server)

I have tested this and it has occurred on several Geyser instances, all from varying builds and platforms. (Bungeecord/Waterfall, Spigot, Standalone)

I went back to test and it occurred on a local test server.

Bedrock's POV
![image](https://user-images.githubusercontent.com/67489949/126553184-9afcd263-96c2-4ed8-a567-70d637564f23.png)

Java's POV
![image](https://user-images.githubusercontent.com/67489949/126553215-ef465936-a127-4034-ab83-988b3123d755.png)

``Geyser version 1.4.1-SNAPSHOT (git-master-6b84e07)``
[Geyser Dump](https://dump.geysermc.org/OtTnCpeEymaSMbyOpgT46aym2EKl0EUu)
Floodgate ver. 18
``Paper version git-Paper-121 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b854e7e)``
[Logs just in case.](https://mclo.gs/3cBTJKv)

And no, rejoining the server does not make the skin appear.

**Comment by RedstoneBoy0509** [comment]
I get the same problem, this is probably due to the fact that Bedrock skins are extremely customizable and even have the option to change their model. **MOJANG WILL NEED TO ADD THIS TO JAVA** or Geyser will not be able to send over this model.

**Comment by Konicai** [comment]
If the model is incompatible, Geyser should say it whenever the player connects

**Comment by 7man7LMYT** [comment]
Thing is, this is a skin from the 4th birthday pack. It's not customizable and it doesn't explain why it used to show up on my server before.

**Comment by Wawwior** [comment]
i think this is caused by the MineSkin API is getting many requests lately and takes long to process all of them.

**Comment by 7man7LMYT** [comment]
I don't think that's the cause since my skin is already past the queue.

**Comment by Tim203** [comment]
> i think this is caused by the MineSkin API is getting many requests lately and takes long to process all of them.

We have our own queue, the individual servers don't touch MineSkin endpoints

**Comment by Wawwior** [comment]
> > i think this is caused by the MineSkin API is getting many requests lately and takes long to process all of them.
> 
> We have our own queue, the individual servers don't touch MineSkin endpoints

Didn't know that, but i read the wiki and but the information here. 
+ is there a way to directly use the MineSkin API?

**Comment by Tim203** [comment]
Yes, but you'd have to run your own Global API, which would kinda defeat its purpose.
I'd just recommend waiting like everyone else's doing, your skin is going to be uploaded eventually.

**Comment by Wawwior** [comment]
> Yes, but you'd have to run your own Global API, which would kinda defeat its purpose.
> I'd just recommend waiting like everyone else's doing, your skin is going to be uploaded eventually.

still waiting...

**Comment by Tim203** [comment]
Is this still an issue?

**Comment by 7man7LMYT** [comment]
So far, the skin does now appear, however, there are still some occasions when the skin doesn't show up at all. Even when the skin shows up, it uses the wrong player model for the skin. The skin uses the 'Slim' player model, but the skin appears to use the 'Classic' player model for Java players, which ends up breaking the skin.

**Comment by Orlaando-dev** [comment]
It seems like it breaks on first join and takes two joins to get working.

**Comment by 7man7LMYT** [comment]
Rechecked just now, and it's not even using the right skin for me now, it's still using the wrong model as well.
![image](https://user-images.githubusercontent.com/67489949/163741702-900f4360-5c1d-4cd0-a85a-b625fa590002.png)

**Comment by DeonHarwnart** [comment]
Hi, I just tried Paper 1.19 Experimental Build 1, released today, and this issue seems to be gone. Everything seems to be working fine now.

**Comment by Tim203** [comment]
> So far, the skin does now appear, however, there are still some occasions when the skin doesn't show up at all.

Did this happen on a Spigot server or a proxy with Floodgate between them? There was a bug that affected both BungeeCord and Velocity (#183) which has been fixed.

> It seems like it doesn't show to Java players on first join after restart and takes another join to work. It also seems to always choose the wrong model (classic instead of slim)

The first part describes #183, and the model being wrong is not a Floodgate issue but a Global API issue. However, some changes have been pushed to the Global API which might resolve that issue as well.

I recommend retesting it with a build from the `development` branch to see if this is still an issue.

**Comment by NBS-Paste** [comment]
The skins are still not showing up for me and my friends. We can’t see some of our Bedrock Edition friends’ skin. Did you guys ever find out a solution for this bug?

**Comment by Tim203** [comment]
Are you using the `development` branch or are you using the default download (that's master)?

**Comment by NBS-Paste** [comment]
I’m the default download.

**Comment by NBS-Paste** [comment]
Should I use the development branch, and where could I find it?

**Comment by Tim203** [comment]
You can find the `development` branch downloads here https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/development/

**Comment by HansOffice** [comment]
> 您可以`development`在此处找到分支下载https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/development/

I have encountered the same problem, but it seems that the branch version has no effect. Will this be a long-term problem?

**Comment by 42Willow** [comment]
I'm getting this issue on the latest 1.20 stable build, any updates?

**Comment by letsgoawaydev** [comment]
installing this plugin on both Bungeecord/velocity (if you use it) and the server fixed it for me: https://github.com/Camotoy/GeyserSkinManager/releases/

**Comment by Tim203** [comment]
Is this still an issue with the latest version? There were a few changes to how skins are handled quite a while ago now.

**Comment by frogglen** [comment]
> Is this still an issue with the latest version? There were a few changes to how skins are handled quite a while ago now.

sometimes the skins load and sometimes they don't.

I have to reconnect most of the time to get the skin to load in bedrock.

**Comment by YOMA8338** [comment]
I have the same problem too.
I installed GeyserMC on Velocity,
and I installed floodgate and GeyserSkinManager on Velocity and PaperMC, and the BedrockEdition's skin on the JavaEdition side is displayed with the default skin unless I move the proxy server server once.

**Comment by Tim203** [comment]
That could mean two things: the global api restarted (which isn't the case) or somehow your Geyser instance got disconnected from the skin uploader in a niche situation. I assume it's the latter, in which case that message should only show up like once for one player around when they join.
It shouldn't happen often en shouldn't be the reason why none of the Bedrock players have a skin visible from Java.

**Comment by Mark-Kincaid** [comment]
Hey Tim. This message shows each time a bedrock player connects and no skin has every loaded on bedrock players. Even with latest dev builds

**Comment by Tim203** [comment]
Do you maybe have a firewall blocking connections to `api.geysermc.org` on the device running Geyser? And that the server running Floodgate does not have a firewall rule for it.

**Comment by Doonplex** [comment]
Still reproducible on current builds behind **BungeeCord**, with some extra detail that may help narrow it down:

**Setup:** BungeeCord build 2091 (26.1-R0.1-SNAPSHOT) · Geyser-BungeeCord 2.11.2-b1235 · Floodgate 2.2.5-b140 on the proxy and on the Paper backends (1.18.2 and 1.21.11) · identical `key.pem` · `send-floodgate-data: true` · backends `online-mode=false` + `bungeecord: true`. Bedrock client 26.45, using a Classic Skin Pack skin (not a persona).

**Symptom:** Java players see every Bedrock player as Steve/Alex. Nothing is logged at any level.

**What we verified:**
- The upload side is fine: `GET https://api.geysermc.org/v2/skin/<xuid>` returns a valid Mojang-signed texture, and the PNG is the player's actual skin.
- Floodgate does fire `SkinApplyEvent` on the proxy (visible with SkinsRestorer debug: `Handling Floodgate skin apply for .Name (uuid)`), but the texture never ends up on the forwarded profile.
- It's not SkinsRestorer: it reproduces on a backend with no SkinsRestorer installed, and SR's Floodgate listener only overrides when it already has a stored skin.
- `use-direct-connection` true/false makes no difference.
- The forwarding path itself works. A tiny proxy plugin that, on `PostLoginEvent`, takes the XUID from the Floodgate UUID's low bits, fetches `/v2/skin/<xuid>` and applies that same signed value/signature through SkinsRestorer's API makes the skin show correctly for Java players. So only Floodgate's own apply step is not taking effect on Bungee.

Dump: https://dump.geysermc.org/0djezNbuwduHP0ghXF38OLXXOm9guMT
