### ISSUE TITLE
"linked-players.db" never seems to get created.

### ISSUE THREAD

**Issue by LoudSoftware** [GeyserMC/Floodgate#29]
Using latest build of: [floodgate-bungee](https://ci.nukkitx.com/job/GeyserMC/job/Floodgate/job/development/20/) running on waterfall (a bungee fork)

I have enabled account linking and restarted server, however I get a nullpointerexception thrown by `org.geysermc.floodgate.link.SQLitePlayerLink.lambda$isLinkedPlayer$1(SQLitePlayerLink.java:60)` anytime I try to run `linkaccount` from within java edition, which makes sense since there isn't a sqlite db in the plugin folder.

Looking at the code, I don't seem to see any mention of creating the `linked-players.db` sqlite database, only connections and queries against it.

Full stack trace:
```
waterfall_1    | [12:57:45 ERROR] [floodgate-bungee]: Error while checking if player is a LinkedPlayer
waterfall_1    | java.lang.NullPointerException: null
waterfall_1    |        at org.geysermc.floodgate.link.SQLitePlayerLink.lambda$isLinkedPlayer$1(SQLitePlayerLink.java:60) ~[?:?]
waterfall_1    |        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_212]
waterfall_1    |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
waterfall_1    |        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
waterfall_1    |        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

Update: found the root cause of the problem:
`[13:33:30 ERROR] [floodgate-bungee]: The required class to load the SQLite database wasn't found`

I have tried compiling from scratch and get the same error

**Comment by LoudSoftware** [comment]
after talking with @circuit10 on discord, he mentionned he ran in the same issue because the jar files were getting minimized. Looks like the pom.xml for all the floodgate variants reverted back the having minimizeJar set to true. Setting it to false in floodgate-bungee for example makes account linking work.

**Comment by Heath123** [comment]
Should be fixed with #31

**Comment by rtm516** [comment]
You mean https://github.com/GeyserMC/Floodgate/pull/30

**Comment by Heath123** [comment]
No
> he mentionned he ran in the same issue because the jar files were getting minimized
#31 fixes that

**Comment by Jeebeevee** [comment]
I have te last floodgate-bungee build (https://ci.nukkitx.com/job/GeyserMC/job/Floodgate/job/development/21/) and got the same issue as the issue starter.

**Comment by Tim203** [comment]
See #30

**Comment by Jeebeevee** [comment]
i had seen it and it should be fixed (as i understand), i was thinking it is fixed in the last build. (the one i linked). But i got still the error, from the missing class and the error when a user logged in.

**Comment by jehendeoff** [comment]
It wasn't fixed, personally I just edited the pom.xml for floodgate-bungee and put minimised jar to false, and it's working fine 
(if you don't have maven or doesn't know how to compile it will be a problem)

**Comment by Tim203** [comment]
> It wasn't fixed, personally I just edited the pom.xml for floodgate-bungee and put minimised jar to false, and it's working fine
That's one of the things #30 fixes

**Comment by jehendeoff** [comment]
well not for me, I still had to edit it (I did it like yesterday I think, will check)

**Comment by Tim203** [comment]
Maybe you tried #31?

**Comment by jehendeoff** [comment]
https://github.com/GeyserMC/Floodgate/blob/development/bungee/pom.xml#L65

**Comment by jehendeoff** [comment]
"fixed"

**Comment by Tim203** [comment]
See #30

**Comment by jehendeoff** [comment]
oh yeah didn't check the pull request my bad

**Comment by Tim203** [comment]
![image](https://user-images.githubusercontent.com/14874493/81336325-6ebd6480-90a9-11ea-973a-7b3cfb6b397e.png)

**Comment by jehendeoff** [comment]
> oh yeah didn't check the pull request my bad

**Comment by LoudSoftware** [comment]
Had a  quick look at #30 and can confirm it seems it will fix this issue once merged, however I understand more testing needs to be done on that PR since there are more features/fixes than just the sqlite DB

**Comment by gp-Airee** [comment]
Still not working.

**Comment by Tim203** [comment]
Can you give like any information?
We might be wizards but we still can't read minds :p

**Comment by gp-Airee** [comment]
Still got the SQLite error in Java 11, latest dev build, and the PR that's supposed to fix it. My developer was able to add the SQLite stuff to the jar so I could get it running.

**Comment by Tim203** [comment]
You're still not helping because we still know nothing.

**Comment by DoctorMacc** [comment]
Mainly: what OS are you running? Can you post the specific error you're getting, too?

**Comment by OskarZyg** [comment]
Fresh install does the same for me, the 2 OS's that I have tested are Windows 10 and Raspbian (Debian)
