### ISSUE TITLE
Bungeecord error

### ISSUE THREAD

**Issue by WongIong** [GeyserMC/Floodgate#320]
07:19:33 [INFO] [Geyser-BungeeCord] LiuS Molten has disconnected from the Java server because of 尝试以 Java 版玩家身份登录！Floodgate 设置正确吗？
07:19:33 [SEVERE] com.github.steveice10.mc.protocol.data.UnexpectedEncryptionException: Cannot reply to ClientboundHelloPacket without profile and access token.

07:19:33 [SEVERE] 	at com.github.steveice10.mc.protocol.ClientListener.packetReceived(ClientListener.java:55)

07:19:33 [SEVERE] 	at com.github.steveice10.packetlib.tcp.TcpSession.callPacketReceived(TcpSession.java:156)

07:19:33 [SEVERE] 	at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:377)

07:19:33 [SEVERE] 	at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:28)

07:19:33 [SEVERE] 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

07:19:33 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)

07:19:33 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)

07:19:33 [SEVERE] 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

07:19:33 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)

07:19:33 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)

07:19:33 [SEVERE] 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

07:19:33 [SEVERE] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

07:19:33 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

07:19:33 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)

07:19:33 [SEVERE] 	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)

07:19:33 [SEVERE] 	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834)

07:19:33 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)

07:19:33 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)

07:19:33 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422)

07:19:33 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1400)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)

07:19:33 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)

07:19:33 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)

07:19:33 [SEVERE] 	at io.netty.channel.local.LocalChannel$3.run(LocalChannel.java:185)

07:19:33 [SEVERE] 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)

07:19:33 [SEVERE] 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)

07:19:33 [SEVERE] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)

07:19:33 [SEVERE] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

07:19:33 [SEVERE] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

07:19:33 [SEVERE] 	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by WongIong** [comment]
07:38:41 [WARNING] [Geyser-BungeeCord] Could not translate packet ClientboundSystemChatPacket
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.text.ChatTypeEntry.bedrockChatType()" because the return value of "it.unimi.dsi.fastutil.ints.Int2ObjectMap.get(int)" is null
	at org.geysermc.geyser.translator.protocol.java.JavaSystemChatTranslator.translate(JavaSystemChatTranslator.java:44)
	at org.geysermc.geyser.translator.protocol.java.JavaSystemChatTranslator.translate(JavaSystemChatTranslator.java:35)
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
07:38:41 [SEVERE] java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.text.ChatTypeEntry.bedrockChatType()" because the return value of "it.unimi.dsi.fastutil.ints.Int2ObjectMap.get(int)" is null

07:38:41 [SEVERE] 	at org.geysermc.geyser.translator.protocol.java.JavaSystemChatTranslator.translate(JavaSystemChatTranslator.java:44)

07:38:41 [SEVERE] 	at org.geysermc.geyser.translator.protocol.java.JavaSystemChatTranslator.translate(JavaSystemChatTranslator.java:35)

07:38:41 [SEVERE] 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)

07:38:41 [SEVERE] 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)

07:38:41 [SEVERE] 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)

07:38:41 [SEVERE] 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)

07:38:41 [SEVERE] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)

07:38:41 [SEVERE] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

07:38:41 [SEVERE] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

07:38:41 [SEVERE] 	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Camotoy** [comment]
The second error has been fixed; update Geyser. 

The first error is probably caused by something. You should submit full server logs.

**Comment by WongIong** [comment]
I am using the up-to-date geyser, its downloaded 14/06. Still get this problem
21:41:25 [WARNING] [Geyser-BungeeCord] Could not translate packet ClientboundSystemChatPacket
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.text.ChatTypeEntry.bedrockChatType()" because the return value of "it.unimi.dsi.fastutil.ints.Int2ObjectMap.get(int)" is null
	at org.geysermc.geyser.translator.protocol.java.JavaSystemChatTranslator.translate(JavaSystemChatTranslator.java:44)
	at org.geysermc.geyser.translator.protocol.java.JavaSystemChatTranslator.translate(JavaSystemChatTranslator.java:35)
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
21:41:25 [SEVERE] java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.text.ChatTypeEntry.bedrockChatType()" because the return value of "it.unimi.dsi.fastutil.ints.Int2ObjectMap.get(int)" is null

21:41:25 [SEVERE] 	at org.geysermc.geyser.translator.protocol.java.JavaSystemChatTranslator.translate(JavaSystemChatTranslator.java:44)

21:41:25 [SEVERE] 	at org.geysermc.geyser.translator.protocol.java.JavaSystemChatTranslator.translate(JavaSystemChatTranslator.java:35)

21:41:25 [SEVERE] 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)

21:41:25 [SEVERE] 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)

21:41:25 [SEVERE] 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)

21:41:25 [SEVERE] 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)

21:41:25 [SEVERE] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)

21:41:25 [SEVERE] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

21:41:25 [SEVERE] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

21:41:25 [SEVERE] 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by WongIong** [comment]
The first one maybe cause by the config not loading, it is fixed.

**Comment by Camotoy** [comment]
Please attach a Geyser dump.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by WongIong** [comment]
https://dump.geysermc.org/va93maPZAs6OPtiffojqEFgVp1zKMGaG

**Comment by Camotoy** [comment]
I'm assuming it's FastLogin conflicting here and assuming the player is a paid Java Edition account, so I'm closing. Not much we can do in that case except suggest you remove the plugin.

**Comment by WongIong** [comment]
i removed Fastlogin.
![image](https://user-images.githubusercontent.com/36799194/173707597-006a1c02-0007-43be-9b1f-1279ce41798a.png)
What should i do to fix this?
