### ISSUE TITLE
Velocity's modern forwarding doesn't work in combination with send-floodgate-data

### ISSUE THREAD

**Issue by ImT3chy** [GeyserMC/Floodgate#33]
**Describe the bug**
If velocity is connecting using forwarding-mode = "MODERN"
and you set send-floodgate-data to true on velocity.
Then you will be meat with the measge Can't connect to server <servername>: The server requires you to connect with velocity. wich resaults in you not being able to join

**To Reproduce**
1. Make a velocity server network (make sure to use forwarding mode Modern)
2. Install floodgate (server and proxy) and geyser (proxy only)
3. copy floodgate key to all servers(So they match)
4. open floodgate config and change (send-floodgate-data: false) to true
5. open bedrock and connect.
6. see error message

**Expected behavior**
That floodgate sends trough all the data to the other server and you dont get the Can't connect to server <servername>: The server requires you to connect with velocity when joining.

**Screenshots / Videos**
https://ibb.co/hgSfdgq

**Server Version**
Paper(284) 1.15.2-RO.1-SNAPSHOT

**Floodgate and geyser Version**
Geyser #152 and tested on both Floodgate pr30 and #21 (tested 21 with keyfiles and config from pr30, and with a brand new config and key)

**Minecraft: Bedrock Edition Version**
v1.14.60

**Additional Context**
i did check that i have the proxy ip and not the servers itself. and only happens when the data pass trough is turned on.

**Comment by Tim203** [comment]
Currently we only support forwarding mode legacy as been said [here](https://github.com/GeyserMC/Geyser/wiki/Floodgate) because the legacy mode is basically the same as bungee is using. We might add forwaring mode modern in the future but for now only legacy works.

**Comment by Tim203** [comment]
This should be fixed in Floodgate 2.0

**Comment by Camotoy** [comment]
Fixed in https://github.com/GeyserMC/Floodgate/commit/b20c63fefac0662f8f7c7f4b44c79079ea6c42d1. Let us know if issues still persist.

**Comment by Vidhin05** [comment]
Still getting the same error when using floodgate dev/2.0 #46 with geyser #705

**Comment by Camotoy** [comment]
Can you share the error?

**Comment by Vidhin05** [comment]
It was a mistake on my part. It is working fine now.

**Comment by Projecki** [comment]
I'm experiencing this on Geyser build 714 and floodgate 2.0. Legacy forwarding works fine, though.

**Comment by Konicai** [comment]
Can you share the error?

**Comment by Projecki** [comment]
Sorry, I was on build 7. Build 9 of floodgate 2.0 works
